### ISSUE TITLE
Wrong filepath in hybridization notebook 1_0

### ISSUE THREAD

**Issue by cmutel** [Depart-de-Sentier/Autumn-School-2022#5]
`pylcaio_directory = os.path.join(Path.home(), 'pylcaio_integration_with_brightway')`

Shouldn't this be: 

`pylcaio_directory = os.path.join(Path.home(), 'pylcaio')`

**Comment by michaelweinold** [comment]
Good catch, but this is intentional. The [`pylcaio` OASES repo](https://github.com/OASES-project/pylcaio/tree/master/src) has a typo in a single directory name, which breaks all functions using files from that directory. My quick fix was for all users to clone my fork (with the typo fixed). In future, a PR could be opened to fix it in the OASES repo.

Compare https://github.com/michaelweinold/pylcaio_integration_with_brightway/issues/7 and the PR https://github.com/Depart-de-Sentier/Autumn-School-2022/pull/4 in this repo.

**Comment by cmutel** [comment]
@michaelweinold OK but you clone to `py...with...` and then try to import `py`. Can't we clone your repo to the user directory on the servers with the directory name `pylcaio`; otherwise we need to change the command that adds to `PATH`.

**Comment by michaelweinold** [comment]
> Can't we clone your repo to the user directory on the servers with the directory name pylcaio; otherwise we need to change the command that adds to PATH.

Yes (see https://github.com/Depart-de-Sentier/Autumn-School-2022/pull/7/commits/8ea7ffe2e37d9c6022fd4a919d04f70b94d72cb1).
